import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  translators: [
    {
      name: 'Lucia Wanjiru',
      slug: 'lucia-wanjiru',
      category: 'Sign-Kiswahili',
      image: '/images/translator2.jpg',
      price: 800,
      rating: 3.2,
      numReviews: 10,
      description: 'I will translate Sign language to Kiswahili & vice verser',
    },
    {
      name: 'Daren Wallace',
      slug: 'daren-wallace',
      category: 'Sign-Kikuyu',
      image: '/images/translator3.jpg',
      price: 900,
      rating: 4.5,
      numReviews: 3,
      description: 'I will translate Sign language to Kikuyu & vice verser',
    },
    {
      name: 'Dennis Hobbs',
      slug: 'dennis-hobbs',
      category: 'Sign-English',
      image: '/images/translator4.jpg',
      price: 950,
      rating: 2.9,
      numReviews: 1300,
      description: 'I will translate Sign language to English & vice verser',
    },
    {
      name: 'Geogina Alex',
      slug: 'geogina-alex',
      category: 'Sign-Kiswahili',
      image: '/images/translator5.jpg',
      price: 950,
      rating: 3.5,
      numReviews: 7,
      description: 'I will translate Sign language to Kiswahili & vice verser',
    },
    {
      name: 'Christine Dale',
      slug: 'christine-dale',
      category: 'Sign-Kikuyu',
      image: '/images/translator6.jpg',
      price: 750,
      rating: 2.4,
      numReviews: 14,
      description: 'I will translate Sign language to Kiswahili & vice verser',
    },

    {
      name: 'Johnathan Kalonzo',
      slug: 'johnathan-kalonzo',
      category: 'Sign-Kamba',
      image: '/images/translator7.jpg',
      price: 1650,
      rating: 4.4,
      numReviews: 7,
      description:
        'I will efficiently translate Sign language to Kamba & vice verser',
    },
    {
      name: 'Sebastien Cliff',
      slug: 'sebastien-cliff',
      category: 'Sign-English',
      image: '/images/translator8.jpg',
      price: 1000,
      rating: 5.0,
      numReviews: 12,
      description: 'I will translate Sign language to English & vice verser',
    },
    {
      name: 'Clair Hellen',
      slug: 'clair-hellen',
      category: 'Sign-English',
      image: '/images/translator9.jpg',
      price: 1050,
      rating: 4.0,
      numReviews: 24,
      description: 'I will translate Sign language to English & vice verser',
    },
    {
      name: 'Irene Anyango',
      slug: 'irene-anyango',
      category: 'Sign-Luo',
      image: '/images/translator10.jpg',
      price: 2550,
      rating: 4.4,
      numReviews: 9,
      description: 'I will translate Sign language to Luo & vice verser',
    },
    {
      name: 'Cynthia Chepkerui',
      slug: 'cynthia chepkekui',
      category: 'Sign-Kalenjin',
      image: '/images/translator11.jpg',
      price: 1050,
      rating: 3.8,
      numReviews: 14,
      description: 'I will translate Sign language to Kalenjin & vice verser',
    },
    {
      name: 'Brenda Lee',
      slug: 'brenda-lee',
      category: 'Sign-Japannese',
      image: '/images/translator12.jpg',
      price: 2000,
      rating: 4.5,
      numReviews: 1,
      description: 'I will translate Sign language to Japannese & vice verser',
    },
  ],
};

export default data;
